import {randomUUID} from 'node:crypto';
import {transaction} from '@/lib/db';
import {verifyStandardWebhook} from '@/lib/security';
import {commissionAmount} from '@/lib/engine.mjs';
export const runtime='nodejs';
export async function POST(req:Request){const raw=await req.text();if(raw.length>1000000)return new Response('Too large',{status:413});if(!process.env.WHOP_WEBHOOK_SECRET||!verifyStandardWebhook(raw,req.headers.get('webhook-id')||'',req.headers.get('webhook-timestamp')||'',req.headers.get('webhook-signature')||'',process.env.WHOP_WEBHOOK_SECRET))return new Response('Invalid signature',{status:401});try{const event=JSON.parse(raw),d=event.data;const plans:Record<string,string>={};if(process.env.WHOP_PLAN_STARTER)plans[process.env.WHOP_PLAN_STARTER]='starter';if(process.env.WHOP_PLAN_GROWTH)plans[process.env.WHOP_PLAN_GROWTH]='growth';if(process.env.WHOP_PLAN_AGENCY)plans[process.env.WHOP_PLAN_AGENCY]='agency';await transaction(async c=>{const inserted=await c.query("INSERT INTO events(id,provider,payload) VALUES($1,'whop',$2) ON CONFLICT DO NOTHING RETURNING id",['whop:'+req.headers.get('webhook-id'),raw]);if(!inserted.rowCount)return;const mid=event.type.startsWith('membership.')?d.id:d.membership?.id;let sub=mid?(await c.query('SELECT * FROM subscriptions WHERE membership_id=$1 FOR UPDATE',[mid])).rows[0]:null;const wid=d.metadata?.workspace_id;if(!sub&&typeof wid==='string'&&/^[0-9a-f-]{36}$/i.test(wid))sub=(await c.query('SELECT * FROM subscriptions WHERE workspace_id=$1 FOR UPDATE',[wid])).rows[0];if(!sub){await c.query("UPDATE events SET status='unmatched' WHERE id=$1",['whop:'+req.headers.get('webhook-id')]);return;}const plan=plans[d.plan?.id];if(event.type==='payment.succeeded'&&plan){const amount=Number(d.total);if(!Number.isFinite(amount)||amount<0)throw new Error('Bad amount');const p=await c.query("INSERT INTO payments(id,workspace_id,amount,currency,status) VALUES($1,$2,$3,$4,'paid') ON CONFLICT DO NOTHING RETURNING id",[d.id,sub.workspace_id,amount,String(d.currency).toUpperCase()]);await c.query("UPDATE subscriptions SET membership_id=COALESCE($1,membership_id),plan=$2,status='active',updated_at=now() WHERE workspace_id=$3",[mid,plan,sub.workspace_id]);if(p.rowCount){const ref=(await c.query("SELECT r.affiliate_id FROM referrals r JOIN affiliates a ON a.id=r.affiliate_id WHERE r.workspace_id=$1 AND r.created_at>now()-interval '12 months' AND a.status='approved'",[sub.workspace_id])).rows[0];if(ref)await c.query("INSERT INTO commissions(id,payment_id,affiliate_id,amount,currency,available_at) VALUES($1,$2,$3,$4,$5,now()+interval '14 days') ON CONFLICT(payment_id) DO NOTHING",[randomUUID(),d.id,ref.affiliate_id,commissionAmount(amount),String(d.currency).toUpperCase()]);}}
 if(event.type==='membership.deactivated')await c.query("UPDATE subscriptions SET status='inactive',updated_at=now() WHERE workspace_id=$1",[sub.workspace_id]);
 if(event.type==='membership.activated'&&plan)await c.query("UPDATE subscriptions SET status='active',membership_id=$1,plan=$2,updated_at=now() WHERE workspace_id=$3",[mid,plan,sub.workspace_id]);
 if(['refund.created','refund.updated','payment.refunded','dispute.created'].includes(event.type)){const pid=d.payment?.id||d.payment_id||d.id;await c.query("UPDATE payments SET status='review' WHERE id=$1 AND workspace_id=$2",[pid,sub.workspace_id]);await c.query("UPDATE commissions SET status=CASE WHEN status='paid' THEN 'recovery_required' ELSE 'held' END WHERE payment_id=$1",[pid]);}
 await c.query("UPDATE events SET status='processed',workspace_id=$2 WHERE id=$1",['whop:'+req.headers.get('webhook-id'),sub.workspace_id]);});return new Response('OK');}catch(e){console.error('whop_event_failed',e instanceof Error?e.name:'error');return new Response('Failed',{status:500});}}
