import {randomBytes,createHash,scryptSync,timingSafeEqual,createCipheriv,createDecipheriv,createHmac} from 'node:crypto';
export const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
export const token=()=>randomBytes(32).toString('hex');
export function hashPassword(password:string){const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;}
export function checkPassword(password:string,hash:string){const [salt,key]=hash.split(':');if(!salt||!key)return false;const expected=Buffer.from(key,'hex');const actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual);}
function key(){const k=Buffer.from(process.env.ENCRYPTION_KEY||'','hex');if(k.length!==32)throw new Error('ENCRYPTION_KEY_REQUIRED');return k;}
export function encrypt(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key(),iv);const out=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv.toString('hex'),cipher.getAuthTag().toString('hex'),out.toString('hex')].join('.');}
export function decrypt(value:string){const [iv,tag,data]=value.split('.');const d=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'hex'));d.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([d.update(Buffer.from(data,'hex')),d.final()]).toString('utf8');}
export function verifyHmac(body:string,signature:string,secret:string){const wanted='sha256='+createHmac('sha256',secret).update(body).digest('hex');return signature.length===wanted.length&&timingSafeEqual(Buffer.from(signature),Buffer.from(wanted));}
export function verifyStandardWebhook(body:string,id:string,timestamp:string,signature:string,secret:string){if(!id||!timestamp||!Number.isFinite(Number(timestamp))||Math.abs(Date.now()/1000-Number(timestamp))>300)return false;const k=secret.startsWith('whsec_')?Buffer.from(secret.slice(6),'base64'):Buffer.from(secret,'utf8');const expected=createHmac('sha256',k).update(`${id}.${timestamp}.${body}`).digest('base64');return signature.split(' ').some(x=>{if(!x.startsWith('v1,'))return false;const sig=x.slice(3);return sig.length===expected.length&&timingSafeEqual(Buffer.from(sig),Buffer.from(expected));});}
