import {randomUUID} from 'node:crypto';
import {after} from 'next/server';
import {sql,transaction} from '@/lib/db';
import {verifyHmac,digest} from '@/lib/security';
import {matches,selectVariant} from '@/lib/engine.mjs';
import {drainJobs} from '@/lib/worker';
export const runtime='nodejs';
export const maxDuration=60;
export async function GET(req:Request){const q=new URL(req.url).searchParams;return process.env.META_VERIFY_TOKEN&&q.get('hub.mode')==='subscribe'&&q.get('hub.verify_token')===process.env.META_VERIFY_TOKEN?new Response(q.get('hub.challenge')):new Response('Forbidden',{status:403});}
export async function POST(req:Request){const raw=await req.text();if(raw.length>1000000)return new Response('Too large',{status:413});if(!process.env.META_APP_SECRET||!verifyHmac(raw,req.headers.get('x-hub-signature-256')||'',process.env.META_APP_SECRET))return new Response('Invalid signature',{status:401});if(!process.env.DATABASE_URL)return new Response('Setup required',{status:503});try{const payload=JSON.parse(raw);for(const entry of payload.entry||[]){const conn=(await sql("SELECT * FROM connections WHERE provider='instagram' AND external_id=$1",[String(entry.id)])).rows[0];if(!conn)continue;
 for(const change of entry.changes||[]){if(change.field!=='comments')continue;const v=change.value;if(!v?.id||!v.from?.id||String(v.from.id)===String(entry.id))continue;await transaction(async c=>{const inserted=await c.query("INSERT INTO events(id,provider,workspace_id,payload,status) VALUES($1,'meta',$2,$3,'processed') ON CONFLICT DO NOTHING RETURNING id",['comment:'+v.id,conn.workspace_id,JSON.stringify(v)]);if(!inserted.rowCount)return;const automations=await c.query("SELECT * FROM records WHERE workspace_id=$1 AND kind='automations' AND data->>'enabled'='true' ORDER BY created_at",[conn.workspace_id]);for(const a of automations.rows){if(a.data.postId&&a.data.postId!==String(v.media?.id))continue;if(a.data.endsAt&&Date.parse(a.data.endsAt)<Date.now())continue;if(!matches(v.text,a.data.keyword))continue;const variant=selectVariant(String(v.from.id),a.data.reply,a.data.replyB);await c.query("INSERT INTO jobs(id,workspace_id,unique_key,payload) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING",[randomUUID(),conn.workspace_id,`reply:${a.id}:${v.from.id}`,JSON.stringify({connectionId:conn.id,automationId:a.id,commentId:v.id,text:variant.text,variant:variant.variant})]);break;}});}
 for(const event of entry.messaging||[]){if(!event.message?.mid||event.message.is_echo||!event.sender?.id)continue;await transaction(async c=>{const inserted=await c.query("INSERT INTO events(id,provider,workspace_id,payload,status) VALUES($1,'meta',$2,$3,'processed') ON CONFLICT DO NOTHING RETURNING id",['message:'+event.message.mid,conn.workspace_id,JSON.stringify(event)]);if(!inserted.rowCount)return;await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[conn.id+':'+event.sender.id]);let convo=(await c.query("SELECT * FROM records WHERE workspace_id=$1 AND kind='conversations' AND data->>'connectionId'=$2 AND data->>'externalId'=$3 LIMIT 1",[conn.workspace_id,conn.id,String(event.sender.id)])).rows[0];const text=event.message.text||'[وسائط]';const d={connectionId:conn.id,externalId:String(event.sender.id),lastText:text,lastInbound:new Date(event.timestamp||Date.now()).toISOString(),status:'open'};if(!convo){const id=randomUUID();await c.query("INSERT INTO records(id,workspace_id,kind,data) VALUES($1,$2,'conversations',$3)",[id,conn.workspace_id,JSON.stringify(d)]);convo={id};}else await c.query('UPDATE records SET data=data||$1::jsonb,updated_at=now() WHERE id=$2',[JSON.stringify(d),convo.id]);await c.query("INSERT INTO records(id,workspace_id,kind,data) VALUES($1,$2,'messages',$3)",[randomUUID(),conn.workspace_id,JSON.stringify({conversationId:convo.id,text,direction:'in'})]);});}
 }after(async()=>{await drainJobs(2);});return new Response('EVENT_RECEIVED');}catch(e){console.error('meta_event_failed',e instanceof Error?e.name:'error');return new Response('Processing failed',{status:500});}}
