CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,email text UNIQUE NOT NULL,password_hash text NOT NULL,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS workspaces(id uuid PRIMARY KEY,name text NOT NULL,owner_id uuid NOT NULL REFERENCES users(id),settings jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS members(workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('owner','admin','agent','viewer')),PRIMARY KEY(workspace_id,user_id));
CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS records(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,kind text NOT NULL,data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS records_scope ON records(workspace_id,kind,created_at DESC);
CREATE TABLE IF NOT EXISTS connections(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,provider text NOT NULL,external_id text NOT NULL,name text NOT NULL,secret text NOT NULL,expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(provider,external_id));
CREATE TABLE IF NOT EXISTS events(id text PRIMARY KEY,provider text NOT NULL,workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,unique_key text UNIQUE NOT NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,error text,run_at timestamptz NOT NULL DEFAULT now(),locked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS jobs_pending ON jobs(status,run_at);
CREATE TABLE IF NOT EXISTS subscriptions(workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE,membership_id text UNIQUE,plan text NOT NULL DEFAULT 'free',status text NOT NULL DEFAULT 'inactive',updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS affiliates(id uuid PRIMARY KEY,user_id uuid UNIQUE NOT NULL REFERENCES users(id),code text UNIQUE NOT NULL,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS referrals(workspace_id uuid PRIMARY KEY REFERENCES workspaces(id),affiliate_id uuid NOT NULL REFERENCES affiliates(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments(id text PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),amount numeric(12,2) NOT NULL,currency text NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commissions(id uuid PRIMARY KEY,payment_id text UNIQUE NOT NULL REFERENCES payments(id),affiliate_id uuid NOT NULL REFERENCES affiliates(id),amount numeric(12,2) NOT NULL,currency text NOT NULL,status text NOT NULL DEFAULT 'pending',available_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits(key text PRIMARY KEY,count integer NOT NULL DEFAULT 1,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_states(state_hash text PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),user_id uuid NOT NULL REFERENCES users(id),provider text NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS recovery_tokens(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS bookings(id uuid PRIMARY KEY,workspace_id uuid NOT NULL REFERENCES workspaces(id),service_id uuid NOT NULL REFERENCES records(id),staff text NOT NULL,customer text NOT NULL,email text NOT NULL,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'confirmed',cancel_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CHECK(end_at > start_at));
CREATE INDEX IF NOT EXISTS bookings_slots ON bookings(workspace_id,staff,start_at,end_at);
CREATE TABLE IF NOT EXISTS audit(id uuid PRIMARY KEY,workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id),action text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());

-- Server-only access: browser/API roles must never read passwords, sessions or tokens.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.users FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.users FROM PUBLIC;
ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.workspaces FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.workspaces FROM PUBLIC;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.members FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.members FROM PUBLIC;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sessions FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.sessions FROM PUBLIC;
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.records FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.records FROM PUBLIC;
ALTER TABLE public.connections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.connections FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.connections FROM PUBLIC;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.events FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.events FROM PUBLIC;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.jobs FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.jobs FROM PUBLIC;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.subscriptions FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.subscriptions FROM PUBLIC;
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.affiliates FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.affiliates FROM PUBLIC;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.referrals FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.referrals FROM PUBLIC;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.payments FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.payments FROM PUBLIC;
ALTER TABLE public.commissions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.commissions FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.commissions FROM PUBLIC;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.rate_limits FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.rate_limits FROM PUBLIC;
ALTER TABLE public.oauth_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.oauth_states FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.oauth_states FROM PUBLIC;
ALTER TABLE public.recovery_tokens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.recovery_tokens FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.recovery_tokens FROM PUBLIC;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.bookings FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.bookings FROM PUBLIC;
ALTER TABLE public.audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.audit FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE public.audit FROM PUBLIC;
